const notes = require('./notes.js')
const chalk = require('chalk')
const notesmsg = notes()
console.log(notesmsg)
console.log(chalk.green.bgRed.bold("success"))
console.log(chalk.bgRed.inverse("inverse"))